# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01983f49f6b2b0305ac5a4149e283aefabf62b823d74497ba091e0466da3dc442502b883d1d79b46335ef15a6965daa830520bf833fa7260c71ca6784397d2cb

test:
  secret_key_base: c6b72a4c00bb19f73e602f974f820ac16e87c7f06e7dfdec1e18f6298cfee79152279f1de651a2973d3fe6365f2a232638516d518068577317617c8f73551b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
