# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6283b3b003bbd89bd289032cf5d0413254dcb7e917a38294247da4a33af06f4a2653925c455c01878917abd23c5d6186cbaff3e95653c2e4ea0594ebd53ea759

test:
  secret_key_base: 75489d41ebac8028951b8b6204a6a374c7a621a09286147a39a66a771c16e2a0d6d06c55a6abd4decc1681507283df4e2becdc2da94fa1aa05bf4a1e0934b3b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
